"""
Create a daily digest GitHub issue summarizing the content watcher pipeline run.

One issue per day — a scannable summary of all sources checked, insights found,
and links to individual insight issues.
"""

import os
from datetime import datetime, timezone

import httpx
import yaml
from pathlib import Path

SOURCES_FILE = Path("registry/content-sources.yaml")


def format_digest_body(summary: dict, routed_insights: list) -> str:
    """Format the daily digest into a GitHub issue markdown body."""
    now = datetime.now(timezone.utc)
    date_str = now.strftime("%B %d, %Y")

    # Group insights by category
    by_category = {}
    for ri in routed_insights:
        cat = ri.get("category", "unknown")
        by_category.setdefault(cat, []).append(ri)

    # Build insights section
    insights_md = ""
    if routed_insights:
        for cat, items in sorted(by_category.items()):
            insights_md += f"\n### {cat.replace('_', ' ').title()}\n"
            for ri in sorted(items, key=lambda x: x.get("score", 0), reverse=True):
                score = ri.get("score", 0)
                action = ri.get("action", "log_only")
                emoji = "🟢" if action == "auto_issue" else "🟡" if action == "team_triage" else "⚪"
                issue_link = f" → {ri['issue_url']}" if ri.get("issue_url") else ""
                source_name = ri.get("source", {}).get("name", "Unknown")
                episode = ri.get("source", {}).get("episode", "")
                effort = ri.get("effort", "?")

                issue_cell = f"[#{ri['issue_url'].split('/')[-1]}]({ri['issue_url']})" if ri.get("issue_url") else "—"
                insights_md += f"| {emoji} **{score:.2f}** | {ri.get('insight', '')[:120]} | {source_name} | {effort} | {issue_cell} |\n"
    else:
        insights_md = "\n_No insights extracted today._\n"

    # Build errors section
    errors_md = ""
    if summary.get("errors"):
        errors_md = "\n## Errors\n"
        for err in summary["errors"]:
            errors_md += f"- `{err}`\n"

    return f"""## Content Watcher Daily Digest — {date_str}

### Pipeline Summary

| Metric | Count |
|--------|-------|
| Sources checked | {summary.get('sources_checked', 0)} |
| Items fetched | {summary.get('items_fetched', 0)} |
| Insights extracted | {summary.get('insights_extracted', 0)} |
| Issues created | {summary.get('issues_created', 0)} |

### Legend
🟢 Auto-issue (score ≥ 0.85) · 🟡 Team triage (≥ 0.65) · ⚪ Logged only (< 0.65)

## Insights

| Score | Insight | Source | Effort | Issue |
|-------|---------|--------|--------|-------|
{insights_md}
{errors_md}
---
_Generated by content-watcher pipeline at {now.strftime('%H:%M UTC')}_
"""


def create_digest(summary: dict, routed_insights: list) -> dict:
    """Create the daily digest GitHub issue.

    Args:
        summary: Pipeline run summary with sources_checked, items_fetched, etc.
        routed_insights: List of dicts with insight details, action, and issue_url.

    Returns:
        Created issue data from GitHub API.
    """
    config = yaml.safe_load(SOURCES_FILE.read_text())
    repo = config.get("monitor_job", {}).get("github_repo", "ohanafy/ai-ops")

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")

    headers = {
        "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
        "Accept": "application/vnd.github+json",
    }

    body = format_digest_body(summary, routed_insights)
    title = f"[Daily Digest] Content Watcher — {date_str}"

    insights_count = summary.get("insights_extracted", 0)
    if insights_count == 0:
        title += " (quiet day)"

    response = httpx.post(
        f"https://api.github.com/repos/{repo}/issues",
        headers=headers,
        json={
            "title": title,
            "body": body,
            "labels": ["content-digest", "daily"],
        },
    )
    response.raise_for_status()
    return response.json()


if __name__ == "__main__":
    print("Run via: python -m agents.content.agent")
