#!/usr/bin/env bash
# generate-skill-index.sh — Parse all SKILL.md frontmatter and generate docs/skill-index.yaml
# Excludes gstack/ (copies) and _template_v2/ (template)
# Usage: bash scripts/generate-skill-index.sh > docs/skill-index.yaml

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/skills"

# Determine pillar from path
get_pillar() {
  local relpath="$1"
  local inner="${relpath#skills/}"
  local depth
  depth=$(echo "$inner" | awk -F'/' '{print NF}')
  if [ "$depth" -ge 3 ]; then
    echo "$inner" | cut -d'/' -f1
  else
    local skill_name
    skill_name=$(echo "$inner" | cut -d'/' -f1)
    case "$skill_name" in
      ohfy-*) echo "ohanafy" ;;
      sf-*) echo "salesforce" ;;
      tray-*) echo "tray" ;;
      ukg-*) echo "ukg" ;;
      *) echo "workflow" ;;
    esac
  fi
}

# Extract YAML frontmatter from a SKILL.md file
extract_frontmatter() {
  awk '/^---$/ { count++; next } count == 1 { print } count >= 2 { exit }' "$1"
}

# Extract name from frontmatter
extract_name() {
  echo "$1" | awk '/^name:/ { sub(/^name:[[:space:]]*/, ""); print; exit }'
}

# Extract full description (handles multi-line YAML | and > strings)
extract_description() {
  echo "$1" | awk '
    /^description:/ {
      sub(/^description:[[:space:]]*[|>]?[[:space:]]*/, "")
      if ($0 != "") print $0
      in_desc = 1
      next
    }
    in_desc && /^[a-zA-Z_-]+:/ { exit }
    in_desc && /^  / { sub(/^  /, ""); print }
  '
}

# Extract triggers from description text
extract_triggers() {
  echo "$1" | sed -n '/TRIGGER when:/{
    s/.*TRIGGER when:[[:space:]]*//
    s/[.][[:space:]]*DO NOT TRIGGER.*//
    s/[.]$//
    p
    q
  }'
}

# Extract anti-triggers from description text
extract_anti_triggers() {
  echo "$1" | sed -n '/DO NOT TRIGGER when:/{
    s/.*DO NOT TRIGGER when:[[:space:]]*//
    s/[.]$//
    p
    q
  }'
}

# Extract delegate targets from the full SKILL.md file
extract_delegates() {
  # Find markdown links like [sf-lwc](... in Delegate sections
  # Use grep -o with extended regex (works on macOS)
  grep -oE '\[[a-z][a-z0-9-]+\]\(' "$1" 2>/dev/null \
    | sed 's/\[//;s/\](//' \
    | sort -u \
    | grep -v '^http' \
    | head -20 || true
}

# Extract allowed-tools list
extract_tools() {
  echo "$1" | awk '
    /^allowed-tools:/ { in_tools = 1; next }
    in_tools && /^  - / { sub(/^  - /, ""); print }
    in_tools && /^[a-zA-Z_-]+:/ { exit }
  '
}

# Extract a YAML list field (depends_on, chains_to, composable_with, knowledge_refs)
extract_yaml_list() {
  local frontmatter="$1"
  local field="$2"
  echo "$frontmatter" | awk -v f="$field:" '
    $0 ~ f { in_list = 1; next }
    in_list && /^  - / { sub(/^  - /, ""); print }
    in_list && /^[a-zA-Z_-]+:/ { exit }
  '
}

# Escape string for YAML double-quoted context
yaml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g;s/"/\\"/g'
}

# --- Main ---

cat <<'HEADER'
# Skill Index — auto-generated by scripts/generate-skill-index.sh
# Re-generate: bash scripts/generate-skill-index.sh > docs/skill-index.yaml
# Consumed by: orchestrator agent, skill-discovery rule, context-loading protocol

HEADER

echo "generated: \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
echo ""
echo "skills:"

find "$SKILLS_DIR" -name "SKILL.md" \
  -not -path "*/gstack/*" \
  -not -path "*/_template*" \
  | sort | while read -r skill_file; do

  relpath="${skill_file#$REPO_ROOT/}"
  pillar=$(get_pillar "$relpath")

  frontmatter=$(extract_frontmatter "$skill_file")
  name=$(extract_name "$frontmatter")

  # Skip if no name field
  [ -z "$name" ] && continue

  description=$(extract_description "$frontmatter")
  triggers=$(extract_triggers "$description")
  anti_triggers=$(extract_anti_triggers "$description")
  tools=$(extract_tools "$frontmatter")
  delegates=$(extract_delegates "$skill_file")
  depends_on=$(extract_yaml_list "$frontmatter" "depends_on")
  chains_to=$(extract_yaml_list "$frontmatter" "chains_to")
  composable_with=$(extract_yaml_list "$frontmatter" "composable_with")
  knowledge_refs=$(extract_yaml_list "$frontmatter" "knowledge_refs")

  # Summary: first meaningful sentence
  summary=$(echo "$description" | head -1 | sed 's/[.] .*/./;s/^[[:space:]]*//')

  echo ""
  echo "  - name: \"$name\""
  echo "    pillar: \"$pillar\""
  echo "    path: \"$relpath\""
  echo "    summary: \"$(yaml_escape "$summary")\""

  if [ -n "$triggers" ]; then
    echo "    triggers: \"$(yaml_escape "$triggers")\""
  fi

  if [ -n "$anti_triggers" ]; then
    echo "    anti_triggers: \"$(yaml_escape "$anti_triggers")\""
  fi

  if [ -n "$delegates" ]; then
    echo "    delegates_to:"
    echo "$delegates" | while read -r d; do
      [ -n "$d" ] && echo "      - \"$d\""
    done
  fi

  if [ -n "$depends_on" ]; then
    echo "    depends_on:"
    echo "$depends_on" | while read -r d; do
      [ -n "$d" ] && echo "      - \"$d\""
    done
  fi

  if [ -n "$chains_to" ]; then
    echo "    chains_to:"
    echo "$chains_to" | while read -r d; do
      [ -n "$d" ] && echo "      - \"$d\""
    done
  fi

  if [ -n "$composable_with" ]; then
    echo "    composable_with:"
    echo "$composable_with" | while read -r d; do
      [ -n "$d" ] && echo "      - \"$d\""
    done
  fi

  if [ -n "$knowledge_refs" ]; then
    echo "    knowledge_refs:"
    echo "$knowledge_refs" | while read -r d; do
      [ -n "$d" ] && echo "      - \"$d\""
    done
  fi

  if [ -n "$tools" ]; then
    echo "    tools:"
    echo "$tools" | while read -r t; do
      [ -n "$t" ] && echo "      - \"$t\""
    done
  fi

done
