#!/usr/bin/env bash
# Sync Tray.io connector knowledge base
#
# Two data sources:
# 1. Public connector catalog (from Tray documentation)
# 2. Active workspace connectors (from Tray GraphQL API)
#
# Usage:
#   bash scripts/sync-tray-connectors.sh             # Preview mode
#   bash scripts/sync-tray-connectors.sh --apply      # Write to knowledge-base/tray/
#   bash scripts/sync-tray-connectors.sh --workspace   # Also query workspace (requires TRAY_MASTER_TOKEN)
#
# Output:
#   knowledge-base/tray/connector-catalog.md
#   knowledge-base/tray/active-connectors.md
#   knowledge-base/tray/last-synced.txt

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KB_DIR="$REPO_ROOT/knowledge-base/tray"
EXISTING_OPS="$REPO_ROOT/docs/integration-guides/TRAY_CONNECTOR_OPERATIONS.md"

MODE="preview"
WORKSPACE=false

for arg in "$@"; do
    case "$arg" in
        --apply) MODE="apply" ;;
        --workspace) WORKSPACE=true ;;
        *) echo "Unknown arg: $arg"; exit 1 ;;
    esac
done

echo "=== Tray Connector Sync ==="
echo "Mode: $MODE"
echo "Workspace query: $WORKSPACE"
echo ""

# Ensure output directory exists
mkdir -p "$KB_DIR"

# ---- 1. Build connector catalog from existing knowledge ----

echo "--- Building connector catalog ---"

# We seed the catalog from TRAY_CONNECTOR_OPERATIONS.md which has detailed
# connector schemas already documented. In future runs, this can be
# enriched by fetching from Tray's public documentation.

CATALOG_FILE="$KB_DIR/connector-catalog.md"

cat > /tmp/tray-connector-catalog.md << 'CATALOG_EOF'
# Tray.io Connector Catalog

Auto-generated by `scripts/sync-tray-connectors.sh`. Do not edit directly.

## CRM

### Salesforce (v8.6)
- **Operations:** create_record, update_record, upsert_record, find_records, find_record_by_id, get_picklist_values, describe_object, bulk_upsert, bulk_query
- **Auth:** OAuth 2.0 (managed by Tray)
- **Notes:** Primary CRM connector. Supports Composite API for batch operations. See `TRAY_CONNECTOR_OPERATIONS.md` for full schema.

### HubSpot
- **Operations:** create_contact, update_contact, find_contacts, create_deal, update_deal, create_company
- **Auth:** OAuth 2.0

### Microsoft Dynamics 365
- **Operations:** CRUD on entities, metadata queries
- **Auth:** OAuth 2.0

## Accounting / ERP

### QuickBooks Online
- **Operations:** create_invoice, update_invoice, find_invoices, create_customer, create_payment, find_items
- **Auth:** OAuth 2.0
- **Notes:** Key integration for Ohanafy accounting sync. See `TRAY_CONNECTOR_OPERATIONS.md`.

### NetSuite
- **Operations:** CRUD on records, saved searches, SuiteQL queries
- **Auth:** Token-based (TBA)
- **Notes:** Used in netsuite-ohanafy project.

### Xero
- **Operations:** create_invoice, update_invoice, find_contacts, create_payment, bank_transactions
- **Auth:** OAuth 2.0
- **Notes:** Used in xero-ohanafy project.

### SAP
- **Operations:** BAPI calls, IDoc processing, RFC function modules
- **Auth:** Basic / OAuth

## Cloud Storage

### AWS S3
- **Operations:** get_object, put_object, list_objects, copy_object, delete_object
- **Auth:** IAM (Access Key + Secret)
- **Notes:** Used for EDI file staging. See `TRAY_CONNECTOR_OPERATIONS.md`.

### Google Drive
- **Operations:** upload_file, download_file, list_files, create_folder, share_file
- **Auth:** OAuth 2.0

### Dropbox
- **Operations:** upload, download, list, search
- **Auth:** OAuth 2.0

### Box
- **Operations:** upload, download, list, search, collaborate
- **Auth:** OAuth 2.0

## Spreadsheets

### Google Sheets
- **Operations:** get_rows, add_row, update_row, find_rows, create_spreadsheet, get_sheet_names
- **Auth:** OAuth 2.0
- **Notes:** Used for reporting outputs. See `TRAY_CONNECTOR_OPERATIONS.md`.

### Microsoft Excel (via OneDrive/SharePoint)
- **Operations:** get_rows, add_row, update_row
- **Auth:** OAuth 2.0

## Communication

### Slack
- **Operations:** send_message, create_channel, list_channels, upload_file, add_reaction
- **Auth:** OAuth 2.0
- **Notes:** Used for integration alerting and notifications.

### Microsoft Teams
- **Operations:** send_message, create_channel, list_teams
- **Auth:** OAuth 2.0

### Email (SMTP/IMAP)
- **Operations:** send_email, read_inbox
- **Auth:** Basic / OAuth

### Twilio
- **Operations:** send_sms, make_call, list_messages
- **Auth:** API Key

## E-Commerce

### Shopify
- **Operations:** CRUD on orders, products, customers, inventory
- **Auth:** OAuth 2.0 / Private App
- **Notes:** Relevant for ohfy-ecom integrations.

### WooCommerce
- **Operations:** CRUD on orders, products, customers
- **Auth:** API Key

## Data / Database

### PostgreSQL
- **Operations:** query, insert, update, delete, execute_stored_procedure
- **Auth:** Connection string

### MySQL
- **Operations:** query, insert, update, delete
- **Auth:** Connection string

### MongoDB
- **Operations:** find, insert, update, delete, aggregate
- **Auth:** Connection string

### Snowflake
- **Operations:** query, insert, bulk_load
- **Auth:** Username/password + account

## EDI / B2B

### SFTP
- **Operations:** upload_file, download_file, list_files, delete_file, move_file
- **Auth:** SSH key / password
- **Notes:** Used for EDI file exchange (X12 850/810/856).

### AS2
- **Operations:** send_message, receive_message
- **Auth:** Certificate-based

## Utility (Built-in)

### HTTP Client
- **Operations:** GET, POST, PUT, PATCH, DELETE, HEAD
- **Auth:** None / Basic / Bearer / OAuth / Custom headers
- **Notes:** Fallback for any API without a dedicated connector.

### Loop
- **Operations:** loop_collection, loop_count, loop_forever
- **Notes:** Iterate over arrays from previous steps.

### Boolean Condition
- **Operations:** evaluate condition with AND/OR logic
- **Notes:** Branching logic in workflows.

### Data Storage
- **Operations:** set, get, delete, list_keys
- **Scopes:** workflow, project, account
- **Notes:** Watermark/delta sync pattern uses this. See `TRAY_CONNECTOR_OPERATIONS.md`.

### Script (Node.js)
- **Operations:** Execute custom JavaScript
- **Available libraries:** lodash, moment-timezone, crypto, Buffer, URL
- **Notes:** Core of Ohanafy's integration scripts. See `integrations/patterns/`.

### Delay
- **Operations:** wait (seconds/minutes), wait_until (datetime)

### Callable Workflow
- **Operations:** trigger another workflow, pass data
- **Notes:** Compose complex integrations from reusable sub-workflows.
CATALOG_EOF

if [ "$MODE" = "preview" ]; then
    echo "Would write: $CATALOG_FILE"
    echo "  $(wc -l < /tmp/tray-connector-catalog.md) lines"
else
    cp /tmp/tray-connector-catalog.md "$CATALOG_FILE"
    echo "Wrote: $CATALOG_FILE"
fi

# ---- 2. Seed capability matrix from existing docs ----

echo ""
echo "--- Building capability matrix ---"

MATRIX_FILE="$KB_DIR/capability-matrix.md"

cat > /tmp/tray-capability-matrix.md << 'MATRIX_EOF'
# Tray Connector Capability Matrix

Detailed operation schemas for connectors used in Ohanafy integrations.
Auto-generated by `scripts/sync-tray-connectors.sh`. Do not edit directly.

For full schemas with code examples, see `docs/integration-guides/TRAY_CONNECTOR_OPERATIONS.md`.

## Salesforce

| Operation | Input Fields | Output | Batch Support |
|-----------|-------------|--------|---------------|
| create_record | sobject, fields | id, success, errors | Yes (Composite) |
| update_record | sobject, id, fields | success, errors | Yes (Composite) |
| upsert_record | sobject, external_id_field, external_id, fields | id, success, created | Yes (Composite) |
| find_records | sobject, conditions | records[] | N/A |
| find_record_by_id | sobject, id | record | N/A |
| describe_object | sobject | fields[], relationships | N/A |
| get_picklist_values | sobject, field | values[] | N/A |
| bulk_upsert | sobject, external_id_field, records | jobId, state | Built-in |
| bulk_query | query (SOQL) | records[] | Built-in |

## QuickBooks Online

| Operation | Input Fields | Output | Batch Support |
|-----------|-------------|--------|---------------|
| create_invoice | customer_ref, line_items | id, doc_number | Yes (batch) |
| update_invoice | id, sparse_update_fields | id, sync_token | Yes (batch) |
| find_invoices | query (SQL-like) | invoices[] | N/A |
| create_customer | display_name, email, phone | id | No |
| create_payment | customer_ref, total_amt, line[] | id | No |

## AWS S3

| Operation | Input Fields | Output | Batch Support |
|-----------|-------------|--------|---------------|
| get_object | bucket, key | body, content_type, metadata | No |
| put_object | bucket, key, body, content_type | etag, version_id | No |
| list_objects | bucket, prefix, max_keys | objects[] | N/A |
| copy_object | source_bucket, source_key, dest_bucket, dest_key | etag | No |
| delete_object | bucket, key | success | No |

## Google Sheets

| Operation | Input Fields | Output | Batch Support |
|-----------|-------------|--------|---------------|
| get_rows | spreadsheet_id, sheet_name, range | rows[][] | N/A |
| add_row | spreadsheet_id, sheet_name, values | updated_range | Yes (append) |
| update_row | spreadsheet_id, sheet_name, range, values | updated_cells | Yes |
| find_rows | spreadsheet_id, sheet_name, column, value | rows[][] | N/A |

## HTTP Client

| Operation | Input Fields | Output | Notes |
|-----------|-------------|--------|-------|
| GET | url, headers, query_params | status, headers, body | Auto-parse JSON |
| POST | url, headers, body | status, headers, body | Supports form/JSON |
| PUT | url, headers, body | status, headers, body | |
| PATCH | url, headers, body | status, headers, body | |
| DELETE | url, headers | status, headers, body | |
MATRIX_EOF

if [ "$MODE" = "preview" ]; then
    echo "Would write: $MATRIX_FILE"
    echo "  $(wc -l < /tmp/tray-capability-matrix.md) lines"
else
    cp /tmp/tray-capability-matrix.md "$MATRIX_FILE"
    echo "Wrote: $MATRIX_FILE"
fi

# ---- 3. Query workspace (if --workspace and token available) ----

echo ""
echo "--- Workspace inventory ---"

ACTIVE_FILE="$KB_DIR/active-connectors.md"

if [ "$WORKSPACE" = true ]; then
    if [ -z "${TRAY_MASTER_TOKEN:-}" ]; then
        echo "TRAY_MASTER_TOKEN not set. Skipping workspace query."
        echo "Set via: export TRAY_MASTER_TOKEN=\$(aws secretsmanager get-secret-value ...)"
    else
        echo "Querying Tray workspace for active solutions and connectors..."

        # Query solutions via GraphQL
        SOLUTIONS_RESPONSE=$(curl -s -X POST https://tray.io/graphql \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $TRAY_MASTER_TOKEN" \
            -d '{"query": "{ viewer { solutions { edges { node { id title description tags } } } } }"}' \
            2>/dev/null || echo '{"error": "failed"}')

        if echo "$SOLUTIONS_RESPONSE" | python3 -c "import sys,json; json.load(sys.stdin)" 2>/dev/null; then
            echo "$SOLUTIONS_RESPONSE" | python3 -c "
import sys, json
from datetime import datetime

data = json.load(sys.stdin)
edges = data.get('data', {}).get('viewer', {}).get('solutions', {}).get('edges', [])

lines = ['# Active Tray Connectors', '']
lines.append(f'Last synced: {datetime.utcnow().strftime(\"%Y-%m-%d %H:%M UTC\")}')
lines.append('')
lines.append('Auto-generated by \`scripts/sync-tray-connectors.sh --workspace\`. Do not edit directly.')
lines.append('')
lines.append('## Solutions')
lines.append('')
lines.append('| # | Solution | Description | Tags |')
lines.append('|---|----------|-------------|------|')

for i, edge in enumerate(edges, 1):
    node = edge.get('node', {})
    title = node.get('title', 'Untitled')
    desc = (node.get('description', '') or '')[:60]
    tags = ', '.join(node.get('tags', []) or [])
    lines.append(f'| {i} | {title} | {desc} | {tags} |')

lines.append('')
lines.append(f'**Total solutions:** {len(edges)}')
print('\n'.join(lines))
" > /tmp/tray-active-connectors.md

            if [ "$MODE" = "apply" ]; then
                cp /tmp/tray-active-connectors.md "$ACTIVE_FILE"
                echo "Wrote: $ACTIVE_FILE"
            else
                echo "Would write: $ACTIVE_FILE"
                echo "  Found $(echo "$SOLUTIONS_RESPONSE" | python3 -c "import sys,json; print(len(json.load(sys.stdin).get('data',{}).get('viewer',{}).get('solutions',{}).get('edges',[])))" 2>/dev/null || echo "?") solutions"
            fi
        else
            echo "Failed to parse Tray API response. Check token validity."
        fi
    fi
else
    # Write a placeholder
    cat > /tmp/tray-active-connectors.md << 'ACTIVE_EOF'
# Active Tray Connectors

Not yet synced from workspace. Run with `--workspace` flag and `TRAY_MASTER_TOKEN` set:

```bash
export TRAY_MASTER_TOKEN=$(aws secretsmanager get-secret-value --secret-id tray/master-token --query SecretString --output text)
bash scripts/sync-tray-connectors.sh --apply --workspace
```

## How to populate

1. Set `TRAY_MASTER_TOKEN` (from AWS Secrets Manager)
2. Run: `bash scripts/sync-tray-connectors.sh --apply --workspace`
3. Commit the generated files
ACTIVE_EOF

    if [ "$MODE" = "apply" ]; then
        cp /tmp/tray-active-connectors.md "$ACTIVE_FILE"
        echo "Wrote: $ACTIVE_FILE (placeholder — run with --workspace to populate)"
    else
        echo "Would write: $ACTIVE_FILE (placeholder)"
    fi
fi

# ---- 4. Write timestamp ----

SYNC_FILE="$KB_DIR/last-synced.txt"
if [ "$MODE" = "apply" ]; then
    date -u '+%Y-%m-%dT%H:%M:%SZ' > "$SYNC_FILE"
    echo ""
    echo "Wrote: $SYNC_FILE"
fi

# ---- Summary ----
echo ""
echo "=== Sync complete ==="
if [ "$MODE" = "preview" ]; then
    echo "Run with --apply to write files to knowledge-base/tray/"
else
    echo "Files written to: $KB_DIR/"
    ls -la "$KB_DIR/"
fi
