"""
GitHub issue creation for the repo-watchers pipeline.

Creates structured issues for items that score above the notify threshold.
"""

import logging
import os

import httpx

from .schema import RouteAction, RoutedItem

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"
DEFAULT_REPO = "dzeder/daniels-ohanafy"
ISSUE_LABEL = "ai-ops-adoption"
AUTO_ADOPT_LABEL = "auto-adopt-candidate"


def _format_issue_body(item: RoutedItem) -> str:
    """Format a routed item into a GitHub issue markdown body."""
    skills_section = "None detected"
    if item.affected_skills:
        skills_section = "\n".join(
            f"- `{s.skill_path}` (adapted: {s.adapted_date or 'unknown'})"
            for s in item.affected_skills
        )

    auto_adopt_value = item.metadata.get("auto_adopt", "unknown")
    if item.action == RouteAction.auto_issue:
        next_step = "High-confidence match — review for auto-adoption"
    else:
        next_step = "Manual review recommended"

    return f"""## Source
- **Repo:** [{item.repo}](https://github.com/{item.repo})
- **Category:** {item.metadata.get('category', 'unknown')}
- **Priority:** {item.metadata.get('priority', 'unknown')}
- **Type:** {item.item_type.value}
- **URL:** {item.url}
- **Published:** {item.published_at or 'unknown'}

## What Changed
{item.body[:2000]}

## Why It Matters
{item.reason}

## Relevance Score: {item.score:.2f}

## Affected Skills (Lineage)
{skills_section}

## Auto-Adopt Policy: {auto_adopt_value}

## Recommended Next Step
{next_step}

---
*Generated by [Repo Watcher](https://github.com/{DEFAULT_REPO})*
"""


def create_issue(
    item: RoutedItem,
    github_repo: str = DEFAULT_REPO,
) -> str | None:
    """Create a GitHub issue for a routed item.

    Returns the issue HTML URL on success, None on failure.
    """
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        logger.error("GITHUB_TOKEN not set, skipping issue creation")
        return None

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    title = f"[Repo Watcher] {item.repo} — {item.title[:60]}"
    body = _format_issue_body(item)

    labels = [ISSUE_LABEL]
    if item.action == RouteAction.auto_issue:
        labels.append(AUTO_ADOPT_LABEL)

    try:
        resp = httpx.post(
            f"{GITHUB_API}/repos/{github_repo}/issues",
            headers=headers,
            json={"title": title, "body": body, "labels": labels},
            timeout=30.0,
        )
        resp.raise_for_status()
        issue_url = resp.json().get("html_url", "")
        logger.info("Created issue: %s", issue_url)
        return issue_url
    except httpx.HTTPStatusError as e:
        logger.error("Failed to create issue for %s: %s", item.title[:60], e)
        return None
